### ISSUE TITLE
update for rtamt 0.2.x

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt4ros#11]
Please see branch pre0.2.x. I find problem when connecting prototype rtamt to rtamt4ros.  

```
$ roslaunch rtamt4ros ros_stl_monitor_with_API.launch 
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu1804:35339/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    ros_stl_monitor (rtamt4ros/ros_stl_monitor_with_API.py)
    signal_generator (systems/signal_generator)

ROS_MASTER_URI=http://localhost:11311

process[signal_generator-1]: started with pid [29330]
process[ros_stl_monitor-2]: started with pid [29331]
Traceback (most recent call last):
  File "/mnt/data/repos/rtamt4ros_ws/src/rtamt4ros/rtamt4ros/scripts/ros_stl_monitor_with_API.py", line 93, in <module>
    monitor(args.period, args.unit)
  File "/mnt/data/repos/rtamt4ros_ws/src/rtamt4ros/rtamt4ros/scripts/ros_stl_monitor_with_API.py", line 29, in monitor
    spec.declare_var('a', 'FloatMessage')
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/ltl/discrete_time/specification.py", line 114, in declare_var
    instance = self.create_var_from_name(var_name)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/ltl/discrete_time/specification.py", line 142, in create_var_from_name
    var_module = self.spec.modules[var_type]
AttributeError: 'NoneType' object has no attribute 'modules'
[ros_stl_monitor-2] process has died [pid 29331, exit code 1, cmd /mnt/data/repos/rtamt4ros_ws/src/rtamt4ros/rtamt4ros/scripts/ros_stl_monitor_with_API.py --period 1 --unit 1 __name:=ros_stl_monitor __log:=/home/tomoya/.ros/log/6d7a6cac-4fa4-11eb-a67d-ccf9e4d4d4e7/ros_stl_monitor-2.log].
log file: /home/tomoya/.ros/log/6d7a6cac-4fa4-11eb-a67d-ccf9e4d4d4e7/ros_stl_monitor-2*.log
^C[signal_generator-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

I guess,
```python
spec.declare_var('a', 'FloatMessage')
```
especially importing ROS data structure "FloatMessage" is not imported.

**Comment by TomyYamy** [comment]
Perhaps, I can skip to use 'FloatMessage' in temporally. because I can covert it in to float in my side.

Essentially, we can discuss where we need to handle such ROS stuff.
Now we are handling it RTAMT side like,
```python
self.spec.import_module('rtamt_msgs.msg', 'FloatMessage')
self.spec.set_var_topic('c', 'rtamt/c')
```
But architecture perspective we had better to handle it in rtamt4ros.

**Comment by TomyYamy** [comment]
I remember why we implement
```python
self.spec.set_var_topic('c', 'rtamt/c')
```
is to handle multi STL formulas with different nodes. Each STL node can publish their own robustness.
Problem is what is our recommendation when we handle multi STL formulas. now we have
```python
spec.add_sub_spec('c = a + b')
```

**Comment by TomyYamy** [comment]
I added 
ros_stl_monitor_with_API2.py
commit: 27274b8ebe843b1f3ac5031f42325145512200bd

The intention is once avoiding ros harness functionality in rtamt.
 But there seem to have update error when we update spec with ROS time stamp.
 
 ```
 $ roslaunch rtamt4ros ros_stl_monitor_with_API2.launch 
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu1804:46245/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    ros_stl_monitor (rtamt4ros/ros_stl_monitor_with_API2.py)
    signal_generator (systems/signal_generator)

ROS_MASTER_URI=http://localhost:11311

process[signal_generator-1]: started with pid [9474]
process[ros_stl_monitor-2]: started with pid [9475]
[INFO] [1609965796.902050]: a: time:1609965796594340425 value:0.002
[INFO] [1609965796.911958]: []
[INFO] [1609965797.901679]: a: time:1609965797594345400 value:0.003
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/timer.py", line 234, in run
    self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))
  File "/mnt/data/repos/rtamt4ros_ws/src/rtamt4ros/rtamt4ros/scripts/ros_stl_monitor_with_API2.py", line 54, in monitor_callback
    rob = self.spec.update(['a', a_data])
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/dense_time/specification.py", line 82, in update
    out = self.online_evaluator.evaluate(self.top, [])
  File "/usr/local/lib/python2.7/dist-packages/rtamt/evaluator/stl/online_evaluator.py", line 35, in evaluate
    sample = self.visit(node, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/discrete_time/visitor.py", line 44, in visit
    out = self.visitPredicate(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/evaluator/stl/online_evaluator.py", line 49, in visitPredicate
    out_sample = monitor.update(in_sample_1, in_sample_2)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/operation/stl/dense_time/online/predicate_operation.py", line 15, in update
    input_list = self.sub.update(input_list_1, input_list_2)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/operation/arithmetic/dense_time/online/subtraction_operation.py", line 14, in update
    out, last, left, right = intersect.intersection(self.left, self.right, intersect.subtraction)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/operation/stl/dense_time/online/intersection.py", line 68, in intersection
    if a_end < b_end:
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/rostime.py", line 268, in __cmp__
    raise TypeError('cannot compare to non-Time')
TypeError: cannot compare to non-Time
```

**Comment by TomyYamy** [comment]
I tried

**Comment by TomyYamy** [comment]
I guess it is time stamp issue.
Perhaps overflow at
```python
a_end < b_end:
```
Actually ros time stamp has huge number of time and difference too, like
1610031085337687969
1610031086337810039

Actually the huge number was fine. Maybe huge time difference gives error. I tried  small difference, like
1610031085337687969
1610031085337687970
It works.

**Comment by nickovic** [comment]
I fixed several issues:
- you should not directly pass ROS time, you should first convert it to a float (either useng .to_sec() or to_nsec() method
- When one wants to use complex data structures, such as FloatMessage, one should use the following flow:
- self.spec.import_module('rtamt_msgs.msg', 'FloatMessage')
  self.spec.declare_var('a', 'FloatMessage')
  self.spec.spec = 'c = always [0, 5] (a.value <= 2)'

You should not forget to use 'a.value' in the specification itself, rather than 'a', otherwise the tool does not know which field to use.

For the fixed version of rtamt4ros/ros_stl_monitor_with_API2.py, please first intall the latest commit (adf1d620ba09ec1fe521f3eb542db3db272c4dc3) of the rtamt library (branch 12-specification-nesting)

**Comment by TomyYamy** [comment]
I'm looking.
I hope I did 
```python
self.spec.set_var_topic('a', 'float')
```
in that time.

**Comment by TomyYamy** [comment]
I tried your commit, 571d3bbe07f90da426a997a38bce5f41495c89bc
but it does not work.
I feel problem is not "float" or "FloatMessage".

**Comment by TomyYamy** [comment]
I tried new rtamt 991607f too. but it does not work.

```bash
$ roslaunch rtamt4ros ros_stl_monitor_with_API2.launch 
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu1804:44961/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    ros_stl_monitor (rtamt4ros/ros_stl_monitor_with_API2.py)
    signal_generator (systems/signal_generator)

auto-starting new master
process[master]: started with pid [8744]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 51229180-5664-11eb-a38f-ccf9e4d4d4e7
process[rosout-1]: started with pid [8755]
started core service [/rosout]
process[signal_generator-2]: started with pid [8758]
process[ros_stl_monitor-3]: started with pid [8763]
Traceback (most recent call last):
  File "/mnt/data/repos/rtamt4ros_ws/src/rtamt4ros/rtamt4ros/scripts/ros_stl_monitor_with_API2.py", line 69, in <module>
    monitor = Monitor()
  File "/mnt/data/repos/rtamt4ros_ws/src/rtamt4ros/rtamt4ros/scripts/ros_stl_monitor_with_API2.py", line 43, in __init__
    var_object = self.spec.get_var_object(self.spec.out_var)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/abstract_specification.py", line 193, in get_var_object
    return self.var_value_dict[name]
AttributeError: 'STLDenseTimeSpecification' object has no attribute 'var_value_dict'
[ros_stl_monitor-3] process has died [pid 8763, exit code 1, cmd /mnt/data/repos/rtamt4ros_ws/src/rtamt4ros/rtamt4ros/scripts/ros_stl_monitor_with_API2.py --freq 1 __name:=ros_stl_monitor __log:=/home/tomoya/.ros/log/51229180-5664-11eb-a38f-ccf9e4d4d4e7/ros_stl_monitor-3.log].
log file: /home/tomoya/.ros/log/51229180-5664-11eb-a38f-ccf9e4d4d4e7/ros_stl_monitor-3*.log
```

**Comment by TomyYamy** [comment]
OK, with rtamt 1b0f010, it works.

**Comment by TomyYamy** [comment]
@nickovic 
```bash
roslaunch rtamt4ros ros_stl_monitor_with_API.launch
```
does not work. just we did not update it. Do you expect discrete online STL in here?
I think you can check ros harness codes like,
```python
    spec.import_module('rtamt_msgs.msg', 'FloatMessage')
    spec.declare_var('a', 'FloatMessage')
```

**Comment by TomyYamy** [comment]
@nickovic 
I think now in 7f7cdd3c188e197e2658621b83117f01b7d20675
```bash
roslaunch rtamt4ros ros_stl_monitor_with_API.launch
```
express something minimal set what I want to do in ROS. Unsync update in each subscriber and read rob in main loop.

**Comment by TomyYamy** [comment]
@nickovic
I find suspicious behavior. but stil it works.
Please see ab255e5e776d69adffca2ecf09d886c3ee68ccfa
```bash
roslaunch rtamt4ros ros_stl_monitor_with_API2.launch
```
Just I add additional data "b" in spec.
```python
self.spec.spec = 'c = always[0,5]( (a<=2) and (b >= 3) )'
```
some error happens, but the node still works.
```bash
$ roslaunch rtamt4ros ros_stl_monitor_with_API2.launch 
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu1804:38353/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    ros_stl_monitor (rtamt4ros/ros_stl_monitor_with_API2.py)
    signal_generator (systems/signal_generator)

ROS_MASTER_URI=http://localhost:11311

process[signal_generator-1]: started with pid [8608]
process[ros_stl_monitor-2]: started with pid [8609]
[ERROR] [1610646617.287601]: bad callback: <bound method Monitor.a_callback of <__main__.Monitor object at 0x7fad72bf3fd0>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/mnt/data/repos/rtamt4ros_ws/src/rtamt4ros/rtamt4ros/scripts/ros_stl_monitor_with_API2.py", line 57, in a_callback
    rob = self.spec.update(['a', a_data])
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/dense_time/specification.py", line 89, in update
    out = self.online_evaluator.evaluate(self.top, [])
  File "/usr/local/lib/python2.7/dist-packages/rtamt/evaluator/stl/online_evaluator.py", line 35, in evaluate
    sample = self.visit(node, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/discrete_time/visitor.py", line 104, in visit
    out = self.visitTimedHistorically(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/evaluator/stl/online_evaluator.py", line 315, in visitTimedHistorically
    in_sample = self.visit(node.children[0], args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/discrete_time/visitor.py", line 52, in visit
    out = self.visitAnd(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/evaluator/stl/online_evaluator.py", line 170, in visitAnd
    in_sample_2 = self.visit(node.children[1], args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/discrete_time/visitor.py", line 44, in visit
    out = self.visitPredicate(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/evaluator/stl/online_evaluator.py", line 49, in visitPredicate
    out_sample = monitor.update(in_sample_1, in_sample_2)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/operation/stl/dense_time/online/predicate_operation.py", line 15, in update
    input_list = self.sub.update(input_list_1, input_list_2)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/operation/arithmetic/dense_time/online/subtraction_operation.py", line 11, in update
    self.left = self.left + left_list
TypeError: can only concatenate list (not "float") to list

[INFO] [1610646617.626658]: Robustness: []
[INFO] [1610646618.626359]: Robustness: []
[INFO] [1610646619.626450]: Robustness: []
[INFO] [1610646620.626627]: Robustness: [[1610646617276580381, -2.994]]
[INFO] [1610646621.626661]: Robustness: []
[INFO] [1610646622.626555]: Robustness: [[1610646618276733308, -2.994]]
^C[ros_stl_monitor-2] killing on exit
[signal_generator-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by nickovic** [comment]
I fixed the issue in the rtamt repo

**Comment by TomyYamy** [comment]
It works with the latest rtamt branch master 6555257 !

**Comment by TomyYamy** [comment]
@nickovic Could you update the examples of rtamt4ros in master at least? For open user, it does not work. When do you expect you can do. Please prioritize your deadlines. Even now I can work with branch pre0.2.x

**Comment by TomyYamy** [comment]
@nickovic I think check 
```path
rtamt4ros/specs/spec.stl
```
is good for checking it.

**Comment by TomyYamy** [comment]
we are done
