### ISSUE TITLE
asynchronous topics ROS example

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt4ros#5]
I think I can add un-sync topics ROS example.
Which has different time-driven publisher pubA and pubB for topics A and B, then synchronized subscriber subA and subB are implemented. each subscriber has spec.update(). That should be called asynchronously.

**Comment by TomyYamy** [comment]
I think, 
ros_stl_ct_io_monitor_async_update_with_API.py
is closed to the intention.

**Comment by TomyYamy** [comment]
@nickovic Could you help me?
I'm trying make example what I intend in branch unsycExample. Please try,
```bash
roslaunch rtamt4ros ros_stl_ct_io_monitor_async_update_with_API2.launch
```
at the branch.

My intention is,
1. There are 2 different time driven published topic rtamt/a and rtamt/b.
    rtamt/a: 1Hz count-up 0.001 every step
    rtamt/a: 4Hz count-up 0.003 every step 
2. subscriber try to update them when it is published immediately.
    Please see, ros_stl_ct_io_monitor_async_update_with_API2.py

So I'm facing,
```bash
rtamt4ros_ws/src/rtamt4ros/rtamt4ros$ roslaunch rtamt4ros ros_stl_ct_io_monitor_async_update_with_API2.launch 
... logging to /home/xxx/.ros/log/b4fd2742-bc72-11ea-8c86-6230d4090213/roslaunch-ubuntu18-30670.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu18:35425/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.6

NODES
  /
    ros_stl_monitor (rtamt4ros/ros_stl_ct_io_monitor_async_update_with_API2.py)
    signal_generator_A (rtamt4ros/signal_generator.py)
    signal_generator_B (rtamt4ros/signal_generator.py)

ROS_MASTER_URI=http://localhost:11311

process[signal_generator_A-1]: started with pid [30691]
process[signal_generator_B-2]: started with pid [30692]
process[ros_stl_monitor-3]: started with pid [30693]
[INFO] [1593704510.365849]: Initialized the node STLMonitor
[INFO] [1593704510.367129]: Registering as publisher to topic rtamt/c
[INFO] [1593704510.369324]: Subscribing to topic rtamt/a
[INFO] [1593704510.371954]: Subscribing to topic rtamt/b
[ERROR] [1593704510.522774]: bad callback: <function callback at 0x7f35b927a5d0>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 748, in _invoke_callback
    cb(msg, cb_args)
  File "/mnt/data/repos/rtamt4ros_ws/src/rtamt4ros/rtamt4ros/scripts/ros_stl_ct_io_monitor_async_update_with_API2.py", line 17, in callback
    robustness_msgs = spec.update([var_name, [[var_time, var]]])
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/specification.py", line 41, in update
    out = self.evaluator.evaluate(self.top, ['update'])
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 13, in evaluate
    samples = self.visit(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 54, in visit
    out = self.visitAlways(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 176, in visitAlways
    in_sample = self.visit(element.children[0], args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 44, in visit
    out = self.visitAnd(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 117, in visitAnd
    in_sample_1 = self.visit(element.children[0], args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 36, in visit
    out = self.visitPredicate(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/io_stl_ct/evaluator.py", line 11, in visitPredicate
    out_sample = super(STLIOCTEvaluator, self).visitPredicate(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 28, in visitPredicate
    in_sample_1 = self.visit(element.children[0], args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 38, in visit
    out = self.visitVariable(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 42, in visitVariable
    for var_item in var:
TypeError: 'FloatMessage' object is not iterable

[ERROR] [1593704510.770522]: bad callback: <function callback at 0x7f35b927a5d0>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 748, in _invoke_callback
    cb(msg, cb_args)
  File "/mnt/data/repos/rtamt4ros_ws/src/rtamt4ros/rtamt4ros/scripts/ros_stl_ct_io_monitor_async_update_with_API2.py", line 17, in callback
    robustness_msgs = spec.update([var_name, [[var_time, var]]])
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/specification.py", line 41, in update
    out = self.evaluator.evaluate(self.top, ['update'])
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 13, in evaluate
    samples = self.visit(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 54, in visit
    out = self.visitAlways(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 176, in visitAlways
    in_sample = self.visit(element.children[0], args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 44, in visit
    out = self.visitAnd(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 117, in visitAnd
    in_sample_1 = self.visit(element.children[0], args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 36, in visit
    out = self.visitPredicate(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/io_stl_ct/evaluator.py", line 11, in visitPredicate
    out_sample = super(STLIOCTEvaluator, self).visitPredicate(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 28, in visitPredicate
    in_sample_1 = self.visit(element.children[0], args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 38, in visit
    out = self.visitVariable(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 42, in visitVariable
    for var_item in var:
TypeError: 'FloatMessage' object is not iterable

[ERROR] [1593704511.020546]: bad callback: <function callback at 0x7f35b927a5d0>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 748, in _invoke_callback
    cb(msg, cb_args)
  File "/mnt/data/repos/rtamt4ros_ws/src/rtamt4ros/rtamt4ros/scripts/ros_stl_ct_io_monitor_async_update_with_API2.py", line 17, in callback
    robustness_msgs = spec.update([var_name, [[var_time, var]]])
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/specification.py", line 41, in update
    out = self.evaluator.evaluate(self.top, ['update'])
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 13, in evaluate
    samples = self.visit(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 54, in visit
    out = self.visitAlways(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 176, in visitAlways
    in_sample = self.visit(element.children[0], args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 44, in visit
    out = self.visitAnd(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 117, in visitAnd
    in_sample_1 = self.visit(element.children[0], args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 36, in visit
    out = self.visitPredicate(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/io_stl_ct/evaluator.py", line 11, in visitPredicate
    out_sample = super(STLIOCTEvaluator, self).visitPredicate(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 28, in visitPredicate
    in_sample_1 = self.visit(element.children[0], args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 38, in visit
    out = self.visitVariable(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 42, in visitVariable
    for var_item in var:
TypeError: 'FloatMessage' object is not iterable

[INFO] [1593704513.266127]: Robustness: time: 1593704511.26, value: -0.188, update:a
[INFO] [1593704513.268855]: Robustness: time: 1593704511.27, value: -0.188, update:a
[INFO] [1593704513.271594]: Robustness: time: 1593704511.52, value: -0.188, update:a
[INFO] [1593704513.273783]: Robustness: time: 1593704511.77, value: -0.188, update:a
[INFO] [1593704513.275938]: Robustness: time: 1593704512.02, value: -0.188, update:a
```
Even, rtamt/a subscribing seems to be succeeded,  rtamt/b does not work.
I know maybe it is my ROS side handling issue. Do you have idea?

Anyway do you use VScode debugger on ROS? it is very useful. Even-though, I don't know what is the problem...

**Comment by TomyYamy** [comment]
@nickovic Now it is working. I have a question related to here.
```
    robustness_msgs = spec.update([var_name, [[var_time, var]]])
    for msg in robustness_msgs:
        msg[1].header.stamp = rospy.Time.from_sec(msg[0])
        rospy.loginfo('Robustness: time: {0}, value: {1}, update:{2}'.format(msg[0], msg[1].value, var_name))
        pub.publish(msg[1])
```
I'm not sure the output of spec.update(). I expect just list of [(time, rob),(time, rob),(time, rob),....] or something.
Actually msg has msg = \[float, header\]
Maybe msg\[0\](=float) means time stamp. right?
What I did not understand is why you update header with the timestamp in
```
        msg[1].header.stamp = rospy.Time.from_sec(msg[0])
```
I guess still we can use original header.stamp.

**Comment by TomyYamy** [comment]
rtamt4ros/scripts/ros_stl_monitor_unsync_update.py
supports it.
