### ISSUE TITLE
ros_stl_monitor_with_API.py does not support STLIOCTSpecification()

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt4ros#6]
It still time-index version example.

**Comment by TomyYamy** [comment]
I think, ros_stl_monitor.py also.

**Comment by TomyYamy** [comment]
Please see iss6 [45e2b4e9a4baed06bcc3db2caaf22b7baad20b5e].
I'm trying. But reading ros topics (like rtamt/a) format seems not to work.
I tried normal float. In this case it worked.
 ```
$ rosrun rtamt4ros ros_stl_monitor_with_API.py --period 1 --unit 1
ERROR:root:set_sampling_period: unit 1 is not valid. The unit is set to default (s) value
[INFO] [1592347404.442999]: Initialized the node STLMonitor
[INFO] [1592347404.443969]: Registering as publisher to topic rtamt/c
[INFO] [1592347404.445666]: Subscribing to topic rtamt/a
Traceback (most recent call last):
  File "/mnt/data/repos/rtamt4ros_ws/src/rtamt4ros/rtamt4ros/scripts/ros_stl_monitor_with_API.py", line 99, in <module>
    monitor(args.period, args.unit)
  File "/mnt/data/repos/rtamt4ros_ws/src/rtamt4ros/rtamt4ros/scripts/ros_stl_monitor_with_API.py", line 79, in monitor
    rob = spec.update(['a', [(time_stamp.secs, spec.get_var_object('a'))]])
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/specification.py", line 39, in update
    out = self.evaluator.evaluate(self.top, ['update'])
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 13, in evaluate
    sample = self.visit(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 53, in visit
    out = self.visitAlways(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 158, in visitAlways
    in_sample = self.visit(element.children[0], args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 35, in visit
    out = self.visitPredicate(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/io_stl_ct/evaluator.py", line 11, in visitPredicate
    out_sample = super(STLIOCTEvaluator, self).visitPredicate(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 23, in visitPredicate
    in_sample = self.visit(element.children[0], args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 37, in visit
    out = self.visitVariable(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 33, in visitVariable
    value = operator.attrgetter(element.field)(var)
AttributeError: 'list' object has no attribute 'value'
```

**Comment by nickovic** [comment]
The branch iss6-stliospec contains an example of STLIOCTSpecification integrated with ROS (rtamt4ros/scripts/ros_stl_ct_io_monitor_with_API.py).

The example implements the scenario of asynchronous arrival and collection of inputs, and periodic updates.

**Comment by nickovic** [comment]
Added another example to iss6-stliospec, which integrates STLIOCTSpecification with ROS (rtamt4ros/scripts/ros_stl_ct_io_monitor_async_update_with_API.py).

This example shows how to evaluate the spec each time a new input is received.

**Comment by TomyYamy** [comment]
It works! we can close it after merging those.
