### ISSUE TITLE
ros_stl_monitor.py does not support STLIOCTSpecification()

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt4ros#7]
I'm checking this example with rtamt master [e152433efd7862ffd1f0d54020b04a352f466a3d]

**Comment by TomyYamy** [comment]
Please check iss7 [eadd5dc4a6cafe4c541a9a23b3f0d42d95f07fed]
I guess STLIOCTSpecification() does not support parse from setting file.
The cause of the issue should be,
ros_stl_monitor.py, line 37, 
    spec.parse()
```
$ rosrun rtamt4ros ros_stl_monitor.py --stl src/rtamt4ros/rtamt4ros/specs/spec.stl --period 1 --unit 1
ERROR:root:set_sampling_period: unit 1 is not valid. The unit is set to default (s) value
Traceback (most recent call last):
  File "/mnt/data/repos/rtamt4ros_ws/src/rtamt4ros/rtamt4ros/scripts/ros_stl_monitor.py", line 95, in <module>
    monitor(args.stl, args.period, args.unit)
  File "/mnt/data/repos/rtamt4ros_ws/src/rtamt4ros/rtamt4ros/scripts/ros_stl_monitor.py", line 37, in monitor
    spec.parse()
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/io_stl_ct/specification.py", line 34, in parse
    super(STLIOCTSpecification, self).parse()
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/specification.py", line 27, in parse
    super(STLCTSpecification, self).parse()
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/specification.py", line 67, in parse
    self.visitStlfile(ctx)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/parser/stl/StlParserVisitor.py", line 10, in visitStlfile
    return self.visitChildren(ctx)
  File "/usr/local/lib/python2.7/dist-packages/antlr4/tree/Tree.py", line 71, in visitChildren
    childResult = c.accept(self)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/parser/stl/StlParser.py", line 349, in accept
    return visitor.visitStlSpecification(self)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/specification.py", line 95, in visitStlSpecification
    self.visitChildren(ctx)
  File "/usr/local/lib/python2.7/dist-packages/antlr4/tree/Tree.py", line 71, in visitChildren
    childResult = c.accept(self)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/parser/stl/StlParser.py", line 605, in accept
    return visitor.visitDeclVariable(self)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/parser/stl/StlParserVisitor.py", line 35, in visitDeclVariable
    return self.visitChildren(ctx)
  File "/usr/local/lib/python2.7/dist-packages/antlr4/tree/Tree.py", line 71, in visitChildren
    childResult = c.accept(self)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/parser/stl/StlParser.py", line 769, in accept
    return visitor.visitVariableDeclaration(self)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/io_stl_ct/specification.py", line 65, in visitVariableDeclaration
    super(STLIOSpecification, self).visitVariableDeclaration(ctx)
NameError: global name 'STLIOSpecification' is not defined
```

**Comment by TomyYamy** [comment]
It works! we can close it after merging those.
